-- ────────────────────────────────────────────────────────────────────────────────────────────────────
--  V900__seed_glossary.sql — collections and the trilingual glossary
-- ────────────────────────────────────────────────────────────────────────────────────────────────────
--  GENERATED FILE. Do not edit by hand.
--
--  Regenerate with:  node tools/seed-gen/generate.mjs
--  Staleness check:  node tools/seed-gen/generate.mjs --check     (runs in CI)
--
--  Sources of truth:
--   docs/glossary-trilingual.md §1–§5   (terms, trilingual labels, forbidden renderings, 🔒 sensitivity)
--   specs/eval/kb-manifest.jsonl        (documentType values, and the modal classification/tier per type)
--   docs/04-rag-pipeline.md §15         (chunking strategy and token window per content type)
--
--
-- collection.default_audience is derived, not authored: the manifest has no audience field, and
-- ck_document_classification_reachable forbids CONFIDENTIAL/RESTRICTED content at PUBLIC audience,
-- so any collection whose modal classification is above PUBLIC defaults to AGENT.
-- 
-- Collection names in the three languages are AUTHORED here — no source document carries them —
-- and they are the only invented values in this file. Everything else is parsed or derived.
-- 
-- docs/glossary-trilingual.md §6 (the forbidden-rendering register) and §7 (Derja → MSA) are not
-- term rows: §6 is cross-cutting policy and is seeded by V902 into assistant_config, and §7 is a
-- human-readable excerpt of specs/i18n/derja-msa.json, which V903 seeds in full.

--  Surrogate keys are UUIDv5 of the row's natural key under namespace a1ba4a4a-0000-5000-8000-000000000000,
--  so regeneration is byte-identical and a row has the same id in every environment.
--
--  Inserts are plain, not ON CONFLICT DO NOTHING: a Flyway versioned migration runs exactly once,
--  and a natural-key collision here means the source is wrong. Failing loudly at migrate time is
--  better than silently seeding one row fewer.
-- ────────────────────────────────────────────────────────────────────────────────────────────────────

SET search_path TO albaraka_ai, public;

-- ── collection ───────────────────────────────────────────────────────────────────────────────────
-- 9 collections. chunking_policy holds a JSON object
-- {"strategy","minTokens","maxTokens","rule","source"} so the backoffice can render and edit it;
-- the strategies and token windows are the ones documented in docs/04 §15.
INSERT INTO collection (id, code, name_fr, name_ar, name_en, default_audience, default_classification, default_risk_tier, chunking_policy, description_fr, description_ar, description_en, enabled) VALUES
  ('31013ce2-56b9-55c8-850e-72f0d695d3f5', 'PRODUCT_SHEETS', 'Fiches produits', 'بطاقات المنتجات', 'Product sheets', 'PUBLIC', 'PUBLIC', 'T2_MEDIUM', '{"strategy":"HEADING_BLOCK","minTokens":400,"maxTokens":700,"rule":"heading-aware; one chunk per condition block (éligibilité, montant, durée, marge, garanties, pièces)","source":"docs/04 §15"}', 'Product sheets — 24 manifest chunk(s), 8 document(s). Defaults derived from specs/eval/kb-manifest.jsonl.', 'Fiches produits — valeurs par défaut dérivées de specs/eval/kb-manifest.jsonl.', 'Product sheets — defaults derived from specs/eval/kb-manifest.jsonl.', true),
  ('849122d4-9a39-5bce-ba99-19d3070a1165', 'TARIFFS', 'Barèmes et tarifs', 'التعريفات البنكية', 'Tariff booklets', 'PUBLIC', 'PUBLIC', 'T2_MEDIUM', '{"strategy":"TABLE_ROW","minTokens":80,"maxTokens":200,"rule":"one row = one chunk, never split a table row; the header is repeated in every chunk","source":"docs/04 §15"}', 'Tariff booklets — 5 manifest chunk(s), 2 document(s). Defaults derived from specs/eval/kb-manifest.jsonl.', 'Barèmes et tarifs — valeurs par défaut dérivées de specs/eval/kb-manifest.jsonl.', 'Tariff booklets — defaults derived from specs/eval/kb-manifest.jsonl.', true),
  ('182c6b05-2780-5a85-ad43-4b446c0d016e', 'PROCEDURES', 'Procédures', 'الإجراءات', 'Procedures', 'PUBLIC', 'PUBLIC', 'T1_LOW', '{"strategy":"STEP_SEQUENCE","minTokens":300,"maxTokens":600,"rule":"one numbered step sequence per chunk; steps are never split mid-sequence","source":"docs/04 §15"}', 'Procedures — 2 manifest chunk(s), 1 document(s). Defaults derived from specs/eval/kb-manifest.jsonl.', 'Procédures — valeurs par défaut dérivées de specs/eval/kb-manifest.jsonl.', 'Procedures — defaults derived from specs/eval/kb-manifest.jsonl.', true);
INSERT INTO collection (id, code, name_fr, name_ar, name_en, default_audience, default_classification, default_risk_tier, chunking_policy, description_fr, description_ar, description_en, enabled) VALUES
  ('ccc2f637-eeeb-5f67-aa34-5b25fa9da945', 'REGULATION', 'Textes réglementaires', 'النصوص التشريعية والترتيبية', 'Regulation', 'AGENT', 'INTERNAL', 'T3_HIGH', '{"strategy":"ARTICLE","minTokens":200,"maxTokens":800,"rule":"per article, with the article number carried in heading_path (loi 2016-48, circulaires BCT)","source":"docs/04 §15"}', 'Regulation — 3 manifest chunk(s), 1 document(s). Defaults derived from specs/eval/kb-manifest.jsonl.', 'Textes réglementaires — valeurs par défaut dérivées de specs/eval/kb-manifest.jsonl.', 'Regulation — defaults derived from specs/eval/kb-manifest.jsonl.', true),
  ('4ed97b79-15bb-5b31-aa2e-173f115664e0', 'DIRECTORY', 'Annuaire et agences', 'دليل الوكالات', 'Branch directory', 'PUBLIC', 'PUBLIC', 'T1_LOW', '{"strategy":"TABLE_ROW","minTokens":80,"maxTokens":200,"rule":"one row = one chunk; an agency is retrieved whole or not at all","source":"docs/04 §15"}', 'Branch directory — 4 manifest chunk(s), 1 document(s). Defaults derived from specs/eval/kb-manifest.jsonl.', 'Annuaire et agences — valeurs par défaut dérivées de specs/eval/kb-manifest.jsonl.', 'Branch directory — defaults derived from specs/eval/kb-manifest.jsonl.', true),
  ('acbf1647-733a-5c18-8591-3e66f89143ad', 'GLOSSARY', 'Glossaire', 'المعجم', 'Glossary', 'PUBLIC', 'PUBLIC', 'T3_HIGH', '{"strategy":"ENTRY","minTokens":100,"maxTokens":300,"rule":"one term = one chunk, so a definition is never split from its term","source":"docs/04 §15"}', 'Glossary — 6 manifest chunk(s), 1 document(s). Defaults derived from specs/eval/kb-manifest.jsonl.', 'Glossaire — valeurs par défaut dérivées de specs/eval/kb-manifest.jsonl.', 'Glossary — defaults derived from specs/eval/kb-manifest.jsonl.', true);
INSERT INTO collection (id, code, name_fr, name_ar, name_en, default_audience, default_classification, default_risk_tier, chunking_policy, description_fr, description_ar, description_en, enabled) VALUES
  ('2dff83a8-cb66-5740-bdb3-f15a53b7fd26', 'GUIDES', 'Guides clients', 'أدلة الحرفاء', 'Customer guides', 'PUBLIC', 'PUBLIC', 'T1_LOW', '{"strategy":"HEADING_BLOCK","minTokens":400,"maxTokens":700,"rule":"heading-aware; one chunk per question or section","source":"docs/04 §15"}', 'Customer guides — 4 manifest chunk(s), 2 document(s). Defaults derived from specs/eval/kb-manifest.jsonl.', 'Guides clients — valeurs par défaut dérivées de specs/eval/kb-manifest.jsonl.', 'Customer guides — defaults derived from specs/eval/kb-manifest.jsonl.', true),
  ('66832258-fa36-5f5b-8cf3-8fd9a0d32a8e', 'SHARIA_NOTES', 'Notes et avis du Comité', 'ملاحظات وآراء اللجنة', 'Sharia notes and committee opinions', 'PUBLIC', 'PUBLIC', 'T3_HIGH', '{"strategy":"PARAGRAPH","minTokens":500,"maxTokens":900,"rule":"paragraph-respecting with larger context; the ruling reference is kept intact","source":"docs/04 §15"}', 'Sharia notes and committee opinions — no document in the current manifest; seeded so ingestion cannot fail on a missing collection. Defaults derived from specs/eval/kb-manifest.jsonl.', 'Notes et avis du Comité — valeurs par défaut dérivées de specs/eval/kb-manifest.jsonl.', 'Sharia notes and committee opinions — defaults derived from specs/eval/kb-manifest.jsonl.', true),
  ('82131be2-7d7e-55db-a4ec-9695fb903ad2', 'FAQ', 'Questions fréquentes', 'الأسئلة الشائعة', 'FAQ', 'PUBLIC', 'PUBLIC', 'T1_LOW', '{"strategy":"QA_PAIR","minTokens":100,"maxTokens":300,"rule":"question + answer = one chunk; the question is embedded too, which is a large recall win","source":"docs/04 §15"}', 'FAQ — no document in the current manifest; seeded so ingestion cannot fail on a missing collection. Defaults derived from specs/eval/kb-manifest.jsonl.', 'Questions fréquentes — valeurs par défaut dérivées de specs/eval/kb-manifest.jsonl.', 'FAQ — defaults derived from specs/eval/kb-manifest.jsonl.', true);

-- ── term_glossary ────────────────────────────────────────────────────────────────────────────────
-- 97 terms from docs/glossary-trilingual.md §1–§5. 🔒 in the document becomes
-- sharia_sensitive = true, which routes edits through the T3 path (docs/05 §4).
-- forbidden_renderings is a flat text[]: the column has no per-locale dimension, so the French,
-- Arabic and English prohibited strings from one row are stored together and matched literally by
-- the output guard regardless of the answer language.
-- A trailing parenthetical in a term cell is a gloss, not part of the term: "Murabaha (cost-plus
-- sale)" seeds term_en = 'Murabaha' and definition_en = 'cost-plus sale'. The document's notes
-- column is English, so it seeds definition_en; definition_fr carries only French glosses.
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('3b7608e5-0450-58b4-9f90-1136ac7f2e55', 'MOURABAHA', 'Mourabaha', 'مرابحة', 'Murabaha', NULL, NULL, NULL, 'cost-plus sale. Sale at cost plus a disclosed, agreed margin.', ARRAY['prêt', 'crédit', 'loan', 'interest-bearing sale']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('4bf94db8-bb8b-54e9-9b56-d7f884cf0ad5', 'MOUSSAWAMA', 'Moussawama', 'مساومة', 'Musawama', NULL, NULL, NULL, 'Sale at an agreed price without disclosing cost.', ARRAY['prêt personnel']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('7a23814d-77cc-5b76-84f4-3847d849071d', 'MOUCHARAKA', 'Moucharaka', 'مشاركة', 'Musharaka', NULL, NULL, NULL, 'partnership. Joint capital, shared profit and loss.', ARRAY['crédit participatif', 'joint loan']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('7d7ee07e-97f7-525e-bb15-221951ed0942', 'MOUCHARAKA_DEGRESSIVE', 'Moucharaka dégressive', 'مشاركة متناقصة', 'Diminishing Musharaka', NULL, NULL, NULL, 'Partner progressively buys out the bank''s share', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('eeca7557-b44d-54cc-b25a-cfd463ef7670', 'MOUDHARABA', 'Moudharaba', 'مضاربة', 'Mudaraba', NULL, NULL, NULL, 'Bank provides capital, client provides expertise; profit shared, loss borne by capital.', ARRAY['placement à intérêt']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('eae7d1d6-b227-50be-96da-559dc465a0d8', 'IJARA', 'Ijara', 'إجارة', 'Ijara', NULL, NULL, NULL, 'lease. Lease of an asset or service', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('471013bd-6693-5095-aa3c-d60f647c6c27', 'IJARA_ACQUISITION', 'Ijara assortie de l''option d''acquisition', 'إجارة منتهية بالتمليك', 'Ijara wa Iqtina', NULL, NULL, NULL, 'lease-to-own. As named in loi 2016-48.', ARRAY['crédit-bail classique', 'leasing with interest']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('ff45e4f7-67d4-510b-942e-0ba8c2266c64', 'ISTISNAA', 'Istisna''a', 'استصناع', 'Istisna''a', NULL, NULL, NULL, 'manufacturing/construction contract. Forward contract for something to be built or manufactured', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('5fddb717-dfe4-56af-9378-75454b29b894', 'SALAM', 'Salam', 'سلم', 'Salam', NULL, NULL, NULL, 'forward sale with upfront payment. Full payment at contract, deferred delivery of specified goods', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('1240f27d-9995-5958-b919-0ac09bcdddd6', 'WAKALA', 'Wakala', 'وكالة', 'Wakala', NULL, NULL, NULL, 'agency. Agency mandate; fee must not be a fixed return on capital', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('f9780dc8-68bd-52ce-a1f4-b9dc34b7af8c', 'WAKALA_INVEST', 'Wakala d''investissement', 'وكالة بالاستثمار', 'Investment Wakala', NULL, NULL, NULL, 'Used for placing client funds', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('b742b76a-3799-5263-9ed0-479340222be1', 'BAI_MOUAJJAL', 'Baï Mouajjal', 'بيع مؤجل', 'Deferred-payment sale', NULL, 'vente à terme', NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('b8ae7197-4f5f-5b74-9d84-bee02b19c00e', 'QARD_HASSAN', 'Qard hassan', 'قرض حسن', 'Benevolent loan', NULL, NULL, NULL, 'interest-free. Charity-type lending, no margin', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('16eed8fe-a55d-5409-b70a-e0640d6cc096', 'TAKAFUL', 'Takaful', 'تكافل', 'Takaful', NULL, NULL, NULL, 'cooperative insurance. prohibited when referring to the bank''s cover', ARRAY['assurance classique']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('4a849811-a54a-5374-8e30-e3e044a5b2be', 'SUKUK', 'Sukuk', 'صكوك', 'Sukuk', NULL, NULL, NULL, 'investment certificates', ARRAY['obligations']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'PRODUCT', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('11bc3b58-c57e-5f1f-aa33-0de03f1426e2', 'CHARIA', 'Charia / normes bancaires islamiques', 'الشريعة / المعايير المصرفية الإسلامية', 'Sharia / Islamic banking standards', NULL, NULL, NULL, 'Loi 2016-48 speaks of *normes bancaires islamiques*', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('91aba0a7-455f-5bea-beaf-8842f61fe7ef', 'RIBA', 'riba', 'ربا', 'riba', NULL, 'proscription de l''intérêt', NULL, 'prohibition of interest. Concept, never a product', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('a7de6ef4-be88-55e6-91f5-a7a3dab5cd46', 'GHARAR', 'gharar', 'غرر', 'gharar', NULL, 'incertitude excessive', NULL, 'excessive uncertainty', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('7438d0ed-b7da-5004-97a1-d23673058dbf', 'MAYSIR', 'maysir', 'ميسر', 'maysir', NULL, 'hasard / spéculation', NULL, 'gambling/speculation', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('06972fb6-d06b-5c7a-8afe-51445292c8f9', 'HALAL', 'licite', 'حلال', 'permissible', NULL, 'halal', NULL, 'halal. The assistant never *declares* something halal', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('0a2eae7b-bb7d-5ed3-8886-c6ee0382af6f', 'HARAM', 'illicite', 'حرام', 'prohibited', NULL, 'haram', NULL, 'haram. Same rule', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('57186e64-53bc-5eaf-8fe0-13484b86ebbd', 'FATWA', 'avis religieux', 'فتوى', 'religious ruling', NULL, 'fatwa', NULL, 'fatwa. Reserved to the committee', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('da253359-2792-5ebc-be16-fcaaee1dfe31', 'MARGE_BENEF', 'marge bénéficiaire', 'هامش ربح', 'profit margin', NULL, NULL, NULL, NULL, ARRAY['taux d''intérêt', 'intérêt', 'نسبة فائدة', 'rate of interest']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('5724532c-59e1-5713-9b4c-4cdf5b1b187a', 'PROFIT_SHARE', 'participation aux bénéfices', 'توزيع الأرباح', 'profit sharing', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('363c58cc-d740-54b7-933d-fc08bd2ad8f3', 'NAFAA_AL_AM', 'compte de bienfaisance', 'حساب النفع العام', 'charity account', NULL, 'Nafaa al Am', NULL, 'Where non-conforming income is allocated', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('4c5dbd98-0eb6-573b-bc47-d208e06bf535', 'ZAKAT', 'zakat', 'زكاة', 'zakat', NULL, NULL, NULL, 'Informational only; never a computed ruling', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('04f3828a-2cc7-54a8-9f46-75bc84d6b1bf', 'AAOIFI', 'normes AAOIFI', 'معايير هيئة المحاسبة والمراجعة للمؤسسات المالية الإسلامية', 'AAOIFI standards', NULL, NULL, NULL, 'Cite the standard number when available', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'SHARIA', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('36787652-d257-59a0-a64f-a81ef574a4cc', 'COMPTE_COURANT', 'compte courant', 'حساب جار', 'current account', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('042b425d-f6a2-5fe2-a8a0-1c788e75f008', 'DEPOT_INVEST', 'dépôt d''investissement', 'حساب استثمار', 'investment account', NULL, NULL, NULL, 'IAH', ARRAY['compte à terme rémunéré']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('1a0c6798-5c75-568e-a6d1-92afed76ed2d', 'DEPOT_INVEST_NON_AFFECTE', 'dépôt participatif non affecté', 'وديعة استثمارية غير مخصصة', 'unrestricted investment deposit', NULL, NULL, NULL, 'Profits shared per the agreed key', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('3c0f0e6c-17c8-5eeb-bd89-5517eb4d6501', 'DEPOT_AFFECTE', 'dépôt d''investissement affecté', 'وديعة استثمارية مخصصة', 'restricted investment deposit', NULL, NULL, NULL, 'Tied to a specific operation', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('c89c797f-8ba4-5ec4-9b55-b4ddabfa4f66', 'FINANCEMENT', 'financement', 'تمويل', 'financing', NULL, NULL, NULL, 'prohibited when referring to the bank''s products', ARRAY['crédit', 'prêt', 'loan']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('5c9cbb47-a88f-5648-985c-8c699831d938', 'ENCOURS', 'encours de financements', 'الرصيد الجاري للتمويلات', 'outstanding financing', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('7d9ae4bb-3145-512f-a8e4-16bc2ef1b6b8', 'APPORT_PERSONNEL', 'apport personnel', 'المساهمة الذاتية', 'own contribution / down payment', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('47f94938-7e3e-57f5-8f80-a56b25d06278', 'DUREE_FINANCEMENT', 'durée du financement', 'مدة التمويل', 'financing term', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('e1191b53-a309-5d57-84ab-4891dab49bed', 'ECHEANCE', 'échéance / mensualité', 'قسط', 'instalment', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('31090734-33aa-541a-869a-ff355cf1997a', 'DIFFERE', 'différé de paiement', 'فترة إمهال', 'grace period', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('ecfe4721-b21a-5b69-9b78-888ac13a0693', 'GARANTIE', 'garantie / sûreté', 'ضمان / ضمانات', 'collateral / guarantee', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('a104009d-d087-550d-9d07-5187d8841f30', 'PLAFOND', 'plafond', 'السقف / الحد الأقصى', 'ceiling / limit', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('4ecfb4d0-b6c8-5f36-99e9-171f1331029a', 'DEVIS', 'devis / facture pro forma', 'فاتورة تقديرية', 'quotation / pro forma invoice', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('8738417e-9e58-5aa5-a2f7-79af8d56dc09', 'PIECES_JUSTIF', 'pièces justificatives', 'المؤيدات / الوثائق المطلوبة', 'supporting documents', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('e987f013-3351-5917-b0b8-ed2f6cf75c59', 'CONDITIONS_BANQUE', 'conditions de banque', 'التعرفة البنكية / شروط البنك', 'bank tariff / standard terms', NULL, NULL, NULL, 'Always quoted with its validity date', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('9fbfb2ee-de10-5860-a98d-3a3b42aaa0a6', 'FRAIS_TENUE', 'frais de tenue de compte', 'معاليم مسك الحساب', 'account maintenance fees', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('2d77a13c-046c-5230-be99-7aaddb9c9db1', 'COMMISSION', 'commission', 'عمولة', 'commission / fee', NULL, NULL, NULL, NULL, ARRAY['intérêt']::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('618de826-21e7-53a5-9a69-a3a069c082d1', 'AGENCE', 'agence', 'وكالة', 'branch / agency', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('af54ea68-e507-551f-a0ea-e06fd0f36438', 'HARIF', 'client', 'حريف', 'customer', NULL, NULL, NULL, 'Tunisian banking usage; plural *حرفاء*', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('ecc1f666-28e5-5e4e-bc84-9ce581be4efe', 'CONSEILLER', 'conseiller', 'مستشار', 'advisor', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('bffbece0-429f-5575-bd93-b2f211318a6f', 'RECLAMATION', 'réclamation', 'شكوى / تظلم', 'complaint', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('d3f39ede-96b7-5aa8-bf73-2325fdbde93e', 'CONTRAT', 'contrat', 'عقد', 'contract', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('d15e41af-19fe-5605-b4fe-26402c3a38ea', 'COMITE_CREDIT', 'comité de crédit', 'لجنة التمويل', 'financing committee', NULL, NULL, NULL, 'Internal body', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'FINANCIAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('b9ba850e-17cf-5dd8-9b76-5cc1cfaed777', 'BCT', 'Banque Centrale de Tunisie', 'البنك المركزي التونسي', 'Central Bank of Tunisia', NULL, NULL, NULL, 'Controls conformity of Islamic banking operations with international standards', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('ade933c9-2937-5478-b37f-87da78399939', 'LOI_2016_48', 'Loi n° 2016-48 du 11 juillet 2016', 'القانون عدد 48 لسنة 2016 المؤرخ في 11 جويلية 2016', 'Law No. 2016-48 of 11 July 2016', NULL, NULL, NULL, 'Banks and financial institutions', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('89437a97-3aa8-5015-885c-03bb5fab45e7', 'CIRC_BCT_2021_05', 'Circulaire BCT n° 2021-05 du 19 août 2021', 'منشور البنك المركزي عدد 2021-05 المؤرخ في 19 أوت 2021', 'BCT Circular No. 2021-05', NULL, NULL, NULL, 'Governance, incl. Islamic banking operations', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('d2246a05-8fb7-5f00-b92e-9aa38cad6e58', 'COMITE_CHARIA', 'Comité de contrôle de conformité des normes bancaires islamiques', 'لجنة مراقبة مطابقة المعايير المصرفية الإسلامية', 'Islamic Banking Standards Compliance Committee', NULL, NULL, NULL, 'Loi 2016-48 art. 53–54', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('a9af05d4-1019-5113-a964-3c1ff2dbdd39', 'AUDITEUR_ISLAMIQUE', 'auditeur des opérations bancaires islamiques', 'مدقق العمليات المصرفية الإسلامية', 'Islamic banking operations auditor', NULL, NULL, NULL, 'Circulaire BCT 2021-05', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('7581c72d-8bdd-54b0-a298-9b3c6d4d8d9f', 'JORT', 'Journal Officiel de la République Tunisienne', 'الرائد الرسمي للجمهورية التونسية', 'Official Gazette', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('ba309ea2-5250-5e2d-b685-5275e7c26d37', 'INPDP', 'Instance Nationale de Protection des Données Personnelles', 'الهيئة الوطنية لحماية المعطيات الشخصية', 'National Authority for Personal Data Protection', NULL, NULL, NULL, 'Loi organique 2004-63', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('d84f2278-0bf8-5ba9-98cd-d73f745e3a0e', 'AAOIFI_ORG', 'AAOIFI', 'هيئة المحاسبة والمراجعة للمؤسسات المالية الإسلامية', 'Accounting and Auditing Organization for Islamic Financial Institutions', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', true, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('93e28301-86c3-524e-bfc1-03ab74a21fe2', 'CIBAFI', 'CIBAFI', 'المجلس العام للبنوك والمؤسسات المالية الإسلامية', 'General Council for Islamic Banks and Financial Institutions', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('8b48f521-b1ec-5b2c-9a35-1997bae85d8e', 'ABG', 'Al Baraka Banking Group', 'مجموعة البركة المصرفية', 'Al Baraka Banking Group', NULL, NULL, NULL, 'Parent group', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'GOVERNANCE', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('11330bb0-6e30-5a6b-8d02-5acdcfd25798', 'KB', 'base de connaissances', 'قاعدة المعرفة', 'knowledge base', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('e6b0f4a3-5dc0-581c-b444-89d7422d184b', 'DOCUMENT', 'document', 'وثيقة', 'document', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('7af192d0-e7f0-5ccf-bbff-fb164513c6f5', 'CHUNK', 'extrait / segment', 'مقطع', 'chunk', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('2a7e9a78-19cb-5e81-8560-33b3541c6c76', 'EMBEDDING', 'vecteur de représentation', 'متجه تمثيل نصي', 'embedding', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('96843c9a-d326-5b06-99e9-818c63ce678d', 'RETRIEVAL', 'recherche / récupération', 'استرجاع', 'retrieval', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('7480e10f-6c1f-571e-894d-c10d345e4f52', 'RAG', 'génération augmentée par retrieval', 'التوليد المعزَّز بالاسترجاع', 'retrieval-augmented generation', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('461e5a51-cba6-58dc-96d0-fb1c15d9b39c', 'PROMPT', 'consigne / invite', 'موجِّه', 'prompt', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('d65bc822-8432-584d-80fe-20cda0ff1b15', 'PROMPT_VERSION', 'version de consigne', 'إصدار الموجِّه', 'prompt version', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('5dde11c0-e219-5ab8-b6a1-dd279ee34666', 'GUARDRAIL', 'garde-fou', 'حاجز أمان', 'guardrail', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('fd930cb0-1483-59e5-bd69-1fd7cccbd40e', 'REFUSAL', 'refus / non-réponse', 'امتناع عن الإجابة', 'refusal', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('30bd347a-8ad3-5be3-8218-ef51785cecbc', 'CITATION', 'source citée', 'المصدر المستشهد به', 'citation', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('67d6bb07-7792-502e-bdad-ee48aa268a24', 'DISCLAIMER', 'avertissement', 'تنبيه / إخلاء مسؤولية', 'disclaimer', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('f8b919fc-046e-5f5e-81cc-1aa6f2513130', 'HALLUCINATION', 'réponse non fondée', 'جواب غير مؤصَّل', 'ungrounded answer', NULL, NULL, NULL, 'Prefer "ungrounded" over "hallucination" in user-facing text', '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('c31cf8dd-353e-55a9-a95d-2b75a2dd9e65', 'FEEDBACK', 'retour / évaluation', 'تقييم', 'feedback', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('c362bc3a-f55e-57ac-9c43-9ecd5899575c', 'REVIEW', 'revue / révision', 'مراجعة', 'review', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('33a230f0-c1c0-5ec7-b804-3c635b7f7f5c', 'APPROVAL', 'approbation / visa', 'اعتماد / موافقة', 'approval', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('99cdc85f-f468-592e-95eb-8aa57d48af98', 'TWO_EYES', 'double validation', 'الرقابة المزدوجة', 'four-eyes / two-eyes approval', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('ae0d97d7-c051-59e3-953b-61ea03a2b8af', 'DRAFT', 'brouillon', 'مسودة', 'draft', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('0bcfb57a-7ff9-52a5-8422-f9a159b107ba', 'IN_REVIEW', 'en revue', 'قيد المراجعة', 'in review', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('6ff40786-d023-5fe2-b400-57d3f1fbfb8a', 'SHARIA_APPROVED', 'validé charia', 'معتمد شرعيا', 'Sharia-approved', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('0d5c1dc8-7be9-522d-aee3-6935ed3daa8a', 'PUBLISHED', 'publié', 'منشور', 'published', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('8e7780d8-7b5f-5f2d-8b33-3d464310c441', 'WITHDRAWN', 'retiré', 'مسحوب', 'withdrawn', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('4d04b9c3-f819-5e34-b850-9bd9156d533a', 'DEPRECATED', 'déprécié', 'متروك', 'deprecated', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('c45c2ea1-71b2-5cf1-a66c-4ef22f326c6d', 'AUDIT_TRAIL', 'piste d''audit', 'مسار التدقيق', 'audit trail', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('27a54c20-fb33-5d27-8d22-8d94ec973942', 'EVIDENCE_PACK', 'dossier probatoire', 'ملف الإثباتات', 'evidence pack', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('33e64414-48cf-5f49-aab7-7eb864d20c50', 'GOLDEN_SET', 'jeu de référence', 'مجموعة الاختبار المرجعية', 'golden set', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('ba0df413-3fb0-5ef9-903e-8ad6fb0e8f89', 'EVAL_RUN', 'exécution d''évaluation', 'دورة تقييم', 'evaluation run', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('55278ac9-6204-519c-8c90-4d7d27471a92', 'CANARY', 'diffusion canari', 'نشر تجريبي محدود', 'canary release', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('cf532eb0-6e16-5828-8795-01ce182f332e', 'KILL_SWITCH', 'arrêt d''urgence', 'الإيقاف العاجل', 'kill switch', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('fe8d54ce-d2ad-5af8-8193-bc6ee0d15269', 'COVERAGE_GAP', 'lacune de couverture', 'نقص في التغطية', 'coverage gap', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('072c1064-c63a-5af6-bf3d-64578c925657', 'TERMINOLOGY', 'terminologie', 'المصطلحات', 'terminology', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('99b29f82-16f6-5121-99c2-3cc257143bae', 'FORBIDDEN_RENDERING', 'traduction interdite', 'ترجمة ممنوعة', 'forbidden rendering', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('a7a3017f-1170-51df-b010-730f9740f430', 'DERJA', 'dialecte tunisien', 'العامية التونسية', 'Tunisian dialect', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('aa70cf49-dbd0-5f95-a9b1-cc854681e047', 'MSA', 'arabe littéral', 'العربية الفصحى', 'Modern Standard Arabic', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('0975f203-89c6-5ed1-814d-1df611ec0f41', 'RTL', 'écriture de droite à gauche', 'الكتابة من اليمين إلى اليسار', 'right-to-left', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary'),
  ('1ab77e3c-fdd1-5804-8fed-92d067f676a6', 'HANDOFF', 'transfert vers un conseiller', 'التحويل إلى مستشار', 'handoff', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');
INSERT INTO term_glossary (id, canonical_code, term_fr, term_ar, term_en, transliteration_ar, definition_fr, definition_ar, definition_en, forbidden_renderings, synonyms_fr, synonyms_ar, synonyms_en, domain, sharia_sensitive, status, version, created_by) VALUES
  ('e8e37228-d92e-5105-ad6d-3aa8cdee96c2', 'FATWA_REQUEST', 'demande d''avis au comité', 'طلب رأي من اللجنة', 'committee opinion request', NULL, NULL, NULL, NULL, '{}'::text[], '{}'::text[], '{}'::text[], '{}'::text[], 'TECHNICAL', false, 'ACTIVE', 0, 'flyway:V900__seed_glossary');

-- ── invariants a reviewer can re-run ─────────────────────────────────────────────────────────────
-- SELECT count(*) FROM collection;                                        → 9
-- SELECT count(*) FROM term_glossary;                                     → 97
-- SELECT count(*) FROM term_glossary WHERE sharia_sensitive;              → 33
-- SELECT count(*) FROM term_glossary WHERE cardinality(forbidden_renderings) > 0; → 11
