package tn.albaraka.ai.shared;

public enum IntentCode {
    PRODUCT_QUESTION, PRODUCT_COMPARISON, SHARIA_CONCEPT, RELIGIOUS_RULING_REQUEST, PROCEDURE,
    TARIFF_FEES, BRANCH_LOCATOR, DIGITAL_CHANNEL, ACCOUNT_STATUS, COMPLAINT, SMALL_TALK,
    OUT_OF_SCOPE, ABUSE, ADVERSARIAL
}
